### ISSUE TITLE
no proper flash in the dark

### ISSUE THREAD

**Issue by erkandiken** [googlesamples/android-Camera2Raw#10]
Hi,

I noticed that when ambient illumination differs, flash behaviour also changes. In complete dark, a long prelash is enabled, however, no flash fired.  In a scene with ambient illumination, preflash + flash sequence works properly. Can anybody point out the root cause of not having proper flash in the dark ?

Thanks.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
