### ISSUE TITLE
How to realize camera2 zooming

### ISSUE THREAD

**Issue by nanjidemaomao** [googlesamples/android-Camera2Raw#11]
In  Camera Api，we can use                 
 Camera.Parameters parameters = mCamera.getParameters();
  if (zoomValue < 0) {
                            zoomValue = 0;
                        } else if (zoomValue > parameters.getMaxZoom()) {
                            zoomValue = parameters.getMaxZoom();
                        }
                        parameters.setZoom(zoomValue);
                        mCamera.setParameters(parameters);
these codes to realize zooming camera.
but  how does it do in Camera2 Api ???

Thanks and  wait  for your answer。。

**Comment by AnkanDey** [comment]
Hi,

I am also searching for it. But nothing found. I don't want digital zoom. I want optical zoom feature in my app.

**Comment by paipeng** [comment]
Hello,

I would like to know how to use API for optical zooming, too.

Thank you

**Comment by rsimbu89** [comment]
Hello,
How to add Zoom in and Zoom out feature with CAMERA2 API

**Comment by aasharazeem** [comment]
Did anyone find the how to zoom

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
