### ISSUE TITLE
atypical syntax?

### ISSUE THREAD

**Issue by VirtualCharlie** [googlesamples/android-Camera2Raw#12]
I am puzzled by the if (null == mCameraDevice) syntax on line 944. Am I to read this as equivalent to if  (mCameraDevice == null)? Similar [perplexing uses of " null == " are found in lines 1042 and 1210. Please explain this syntax and point me to appropriate reference materials pertaining to such usage in Java and Android Studio.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
