### ISSUE TITLE
FragmentCompat.OnRequestPermissionsResultCallback 

### ISSUE THREAD

**Issue by VirtualCharlie** [googlesamples/android-Camera2Raw#13]
Using this camera2 code with Android Studio 3.0 (API 27) and Gradle 4.0.1 on my Ubuntu OS, the import android.support.v13.app.FragmentCompat call in the big java file comes up RED with a "cannot resolve" error. So it is no surprise that throughout FragmentCompat comes up RED. Nor can Android Studio find the Android Manifest file which is, in fact, right there in the specified folder!@#$%^. I am trying to implement this camera2 code with the latest android build tools, and I have the requisite library added to the dependencies.

Suggestions?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
