### ISSUE TITLE
android-camera2Raw faisl on AVD

### ISSUE THREAD

**Issue by VirtualCharlie** [googlesamples/android-Camera2Raw#14]
With some tweaking, I have this camera2Raw code able to build with the latest AndroidStudio 3.0.1, and Gradle 4.1, ubuntu OS, however, it will not run on the Pixel = 2 XL API 27 AVD. The app appears loads but immediately STOPS RUNNING. The top story on Logcat: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CameraCharacteristics.get(android.hardware.camera2.CameraCharacteristics$Key)' on a null object 
   Can this AVD be queried for android.hardware.camera2.CameraCharacteristics$<Key>?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
