### ISSUE TITLE
Full screen image

### ISSUE THREAD

**Issue by ShagunParikh** [googlesamples/android-Camera2Raw#17]
Hi,

Is there a way to capture a full-screen image.

I was able to make preview to full screen but the image captured is not. 

It would be very helpful if you could some solution.

**Comment by RKSharma89** [comment]
Hi ShagunParikh,

have you resolved this full screen issue?
can you please provide the way to display preview in full scree.

Thanks

**Comment by yudikarma** [comment]
me to have same problem, please someone reply how to solve

**Comment by yudikarma** [comment]
i found solusition fo this issue, just set adjustbound true and Scaletype fit X,Y to your imageview, but that makes potrait image to strench on landscape mode,
so you have to check rotation firstm if image rotation potrait, dont add adjustbound true and scaletype fit xy, but if rotation Landscape apply that's

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
