### ISSUE TITLE
App has no UI

### ISSUE THREAD

**Issue by sreehax** [googlesamples/android-Camera2Raw#18]
I tried to build this app using ./gradlew build, but all it does is show a full screen preview, with no buttons at the bottom to take a picture.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
