### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by andrewcarmack** [googlesamples/android-Camera2Raw#19]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CameraCharacteristics.get(android.hardware.camera2.CameraCharacteristics$Key)' on a null object reference
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at com.example.android.camera2raw.Camera2RawFragment.configureTransform(Camera2RawFragment.java:1046)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at com.example.android.camera2raw.Camera2RawFragment.access$000(Camera2RawFragment.java:121)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at com.example.android.camera2raw.Camera2RawFragment$1.onSurfaceTextureAvailable(Camera2RawFragment.java:212)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.TextureView.getHardwareLayer(TextureView.java:390)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.TextureView.draw(TextureView.java:339)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18428)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.draw(View.java:19251)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18413)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.draw(View.java:19251)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.draw(View.java:19562)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18428)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.draw(View.java:19251)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18413)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.draw(View.java:19251)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18413)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.draw(View.java:19251)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:840)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.draw(View.java:19562)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:825)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18428)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:681)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:687)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3605)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3382)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2890)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1706)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7806)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1042)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:833)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:768)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1028)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:794)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.os.Looper.TinnoLoop(Looper.java:189)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:270)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6730)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-15 08:25:17.646  6340  6340 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
