### ISSUE TITLE
ChooseOptimalSize too strict

### ISSUE THREAD

**Issue by isVoid** [googlesamples/android-Camera2Raw#24]
I recently ran this app on Red Hydrogen One, and `ChooseOptimalSize` method cannot find a proper preview size. The session fails to configure due to a too high resolution returned (first in choices list).

With further examination I suggest that `ChooseOptimalSize` method is too strict with size filtering, noticeably it requires all sizes to fit with the specified aspect ratio. And this value is provided by getting the `largestJpeg` property from outputs.

On many (high end) devices, max input/output sizes often correspond with the max *native* resolution from sensor array, which is usually a non-standard resolution. In my Red phone's case it's `4056x3040` aka 1.3342105. This is close to 4:3 (1.33) but not exactly. All other lower resolutions are either standard 1.33, 1.77, 1.0, etc.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
