### ISSUE TITLE
Garbage image is being saved  on Portrait mode

### ISSUE THREAD

**Issue by umang6891** [googlesamples/android-Camera2Raw#6]
Garbage image is being saved when device is in portrait mode.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
