### ISSUE TITLE
How to lock AF, AE and AWB?

### ISSUE THREAD

**Issue by mudin3i** [googlesamples/android-Camera2Raw#7]
Hello,

Thank you for the great sample. 
It is very helpful for me to work with camera2 API and raw image support.
Note, It is not an issue, just need help.

After the first shot, how can I lock focus, exposure and white balance?
I tried many things, but no luck.
It would be great, if I someone guides me, and show me the direction.

Thank you in advance

**Comment by prambourg** [comment]
Hey,
You can make change in setup3AControlsLocked, with reference to [this](https://stackoverflow.com/a/28309351) I add at the end of setup3AControlsLocked : 


`
        builder.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_MODE_OFF);
        builder.set(CaptureRequest.SENSOR_EXPOSURE_TIME, 500000000L);
        builder.set(CaptureRequest.SENSOR_SENSITIVITY, 400);
`

Which result with an exposure time of 0,5s and ISO 400 ! For AWB & AF go [here](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html) for more informations :)

**Comment by alpeshprajapati1989** [comment]
I set Exposure time and sensitivity for Camera but cannot resolve camera Can not converge AE and AWB within 150 frames.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
