### ISSUE TITLE
App fails with no useful error when phone doesn't support RAW  

### ISSUE THREAD

**Issue by norlesh** [googlesamples/android-Camera2Raw#8]
Running Camera2Raw on Sony Xperia Z5 Premium all I get is the message "Camera2Raw has stopped" with a button to restart the app and no further information... As it turns out Sony have opted to not support RAW format in there cameras (thank you Sony for restricting me to 23 MP of butchered data).

However the problem here is that the ErrorDialog.show() called from setUpCameraOutputs() is not showing anything before the app is killed off leaving the user unaware of what the problem is/was.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
